
-- Poma Gutierrez Gabriel 23200110

ALTER SESSION SET CURRENT_SCHEMA = HR;
SET SERVEROUTPUT ON;

CREATE TABLE horario (
  dia_semana       NUMBER(1)   NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
  turno            VARCHAR2(20) NOT NULL,
  hora_inicio      DATE         NOT NULL,
  hora_termino     DATE         NOT NULL,
  CONSTRAINT pk_horario PRIMARY KEY (dia_semana, turno),
  CONSTRAINT ck_horario_horas CHECK (hora_termino > hora_inicio)
);

CREATE TABLE empleado_horario (
  employee_id      NUMBER       NOT NULL REFERENCES employees(employee_id),
  dia_semana       NUMBER(1)    NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
  turno            VARCHAR2(20) NOT NULL,
  CONSTRAINT pk_empleado_horario PRIMARY KEY (employee_id, dia_semana),
  CONSTRAINT fk_eh_horario FOREIGN KEY (dia_semana, turno)
    REFERENCES horario (dia_semana, turno)
);

CREATE TABLE asistencia_empleado (
  employee_id       NUMBER      NOT NULL REFERENCES employees(employee_id),
  dia_semana        NUMBER(1)   NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
  fecha_real        DATE        NOT NULL,
  hora_inicio_real  DATE        NOT NULL,
  hora_termino_real DATE        NOT NULL,
  inasistencia      CHAR(1)     DEFAULT 'N' CHECK (inasistencia IN ('S','N')),
  CONSTRAINT pk_asistencia_empleado PRIMARY KEY (employee_id, fecha_real),
  CONSTRAINT ck_asistencia_horas CHECK (hora_termino_real > hora_inicio_real)
);

CREATE TABLE capacitacion (
  capacitacion_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre              VARCHAR2(100) NOT NULL,
  horas               NUMBER(5,2)   NOT NULL CHECK (horas > 0),
  descripcion         VARCHAR2(4000),
  CONSTRAINT pk_capacitacion PRIMARY KEY (capacitacion_id)
);

CREATE TABLE empleado_capacitacion (
  employee_id       NUMBER NOT NULL REFERENCES employees(employee_id),
  capacitacion_id   NUMBER NOT NULL REFERENCES capacitacion(capacitacion_id),
  CONSTRAINT pk_empleado_capacitacion PRIMARY KEY (employee_id, capacitacion_id)
);


INSERT INTO horario VALUES (1,'MATUTINO',  TO_DATE('2000-01-01 07:45','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 11:30','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (1,'VESPERTINO',TO_DATE('2000-01-01 13:30','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 17:45','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (2,'MATUTINO',  TO_DATE('2000-01-01 08:15','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 12:15','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (2,'VESPERTINO',TO_DATE('2000-01-01 14:10','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 18:05','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (3,'MATUTINO',  TO_DATE('2000-01-01 09:10','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 13:10','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (3,'VESPERTINO',TO_DATE('2000-01-01 12:50','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 17:00','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (4,'JORNADA',   TO_DATE('2000-01-01 08:50','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 16:40','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (5,'JORNADA',   TO_DATE('2000-01-01 10:00','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 18:00','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (6,'MATUTINO',  TO_DATE('2000-01-01 07:30','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 11:45','YYYY-MM-DD HH24:MI'));
INSERT INTO horario VALUES (7,'VESPERTINO',TO_DATE('2000-01-01 14:20','YYYY-MM-DD HH24:MI'), TO_DATE('2000-01-01 18:20','YYYY-MM-DD HH24:MI'));

INSERT INTO empleado_horario VALUES (100,1,'MATUTINO');
INSERT INTO empleado_horario VALUES (100,2,'VESPERTINO');
INSERT INTO empleado_horario VALUES (101,1,'VESPERTINO');
INSERT INTO empleado_horario VALUES (101,4,'JORNADA');
INSERT INTO empleado_horario VALUES (102,3,'MATUTINO');
INSERT INTO empleado_horario VALUES (102,5,'JORNADA');
INSERT INTO empleado_horario VALUES (103,3,'VESPERTINO');
INSERT INTO empleado_horario VALUES (104,6,'MATUTINO');
INSERT INTO empleado_horario VALUES (105,7,'VESPERTINO');
INSERT INTO empleado_horario VALUES (106,4,'JORNADA');

INSERT INTO asistencia_empleado VALUES (100, 1, DATE '2025-10-05', TO_DATE('2025-10-05 07:52','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-05 11:33','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (100, 2, DATE '2025-10-06', TO_DATE('2025-10-06 13:36','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-06 17:40','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (101, 1, DATE '2025-10-05', TO_DATE('2025-10-05 13:34','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-05 17:43','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (101, 4, DATE '2025-10-08', TO_DATE('2025-10-08 08:58','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-08 16:41','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (102, 3, DATE '2025-10-07', TO_DATE('2025-10-07 09:12','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-07 13:00','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (102, 5, DATE '2025-10-10', TO_DATE('2025-10-10 10:05','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-10 17:58','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (103, 3, DATE '2025-10-07', TO_DATE('2025-10-07 12:55','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-07 16:50','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (104, 6, DATE '2025-10-11', TO_DATE('2025-10-11 07:36','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-11 11:46','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (105, 7, DATE '2025-10-12', TO_DATE('2025-10-12 14:25','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-12 18:17','YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO asistencia_empleado VALUES (106, 4, DATE '2025-10-08', TO_DATE('2025-10-08 09:05','YYYY-MM-DD HH24:MI'), TO_DATE('2025-10-08 16:38','YYYY-MM-DD HH24:MI'), 'N');

INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Inducción Inicial', 7.5, 'Bienvenida y lineamientos');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Buenas Prácticas TI', 5.5, 'Seguridad y hábitos');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('SQL Intermedio', 10, 'Joins y funciones');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('PL/SQL Aplicado', 15, 'Paquetes y disparadores');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Contenedores Docker', 9, 'Empaquetado');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Orquestación K8s', 13.5, 'Clusters y despliegue');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Scrum Essentials', 8, 'Marco ágil');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Fundamentos UX', 6, 'Interacción básica');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Visualización de Datos', 9.5, 'Gráficos y dashboards');
INSERT INTO capacitacion (nombre, horas, descripcion) VALUES ('Procesos ETL', 11, 'Extracción y carga');

INSERT INTO empleado_capacitacion VALUES (100, 1);
INSERT INTO empleado_capacitacion VALUES (100, 3);
INSERT INTO empleado_capacitacion VALUES (101, 2);
INSERT INTO empleado_capacitacion VALUES (101, 4);
INSERT INTO empleado_capacitacion VALUES (102, 3);
INSERT INTO empleado_capacitacion VALUES (103, 5);
INSERT INTO empleado_capacitacion VALUES (104, 7);
INSERT INTO empleado_capacitacion VALUES (105, 8);
INSERT INTO empleado_capacitacion VALUES (106, 9);
INSERT INTO empleado_capacitacion VALUES (106,10);

COMMIT;


CREATE OR REPLACE PACKAGE hr_pack AS
  PROCEDURE alta_empleado(p_id_emp NUMBER, p_apellido VARCHAR2, p_nombre VARCHAR2,
                          p_correo VARCHAR2, p_f_ingreso DATE, p_puesto VARCHAR2,
                          p_sueldo NUMBER, p_depto NUMBER);

  PROCEDURE leer_empleado(p_id_emp NUMBER, p_cursor OUT SYS_REFCURSOR);

  PROCEDURE actualizar_empleado(p_id_emp NUMBER, p_apellido VARCHAR2 DEFAULT NULL, p_nombre VARCHAR2 DEFAULT NULL,
                                p_correo VARCHAR2 DEFAULT NULL, p_puesto VARCHAR2 DEFAULT NULL,
                                p_sueldo NUMBER DEFAULT NULL, p_depto NUMBER DEFAULT NULL);

  PROCEDURE eliminar_empleado(p_id_emp NUMBER);

  PROCEDURE rotacion_puestos_top4(p_cursor OUT SYS_REFCURSOR);

  FUNCTION promedio_contratos_mensual(p_cursor OUT SYS_REFCURSOR) RETURN NUMBER;

  PROCEDURE reporte_regional(p_cursor OUT SYS_REFCURSOR);

  FUNCTION antiguedad_personal(p_cursor OUT SYS_REFCURSOR) RETURN NUMBER;

  FUNCTION horas_laboradas(p_id_empleado NUMBER, p_mes NUMBER, p_anio NUMBER) RETURN NUMBER;

  FUNCTION horas_ausentes(p_id_empleado NUMBER, p_mes NUMBER, p_anio NUMBER) RETURN NUMBER;

  PROCEDURE nomina_proporcional(p_mes NUMBER, p_anio NUMBER, p_cursor OUT SYS_REFCURSOR);

  FUNCTION horas_formacion_empleado(p_id_empleado NUMBER) RETURN NUMBER;

  PROCEDURE listado_formaciones(p_cursor OUT SYS_REFCURSOR);
END hr_pack;
/


CREATE OR REPLACE PACKAGE BODY hr_pack AS

  PROCEDURE alta_empleado(p_id_emp NUMBER, p_apellido VARCHAR2, p_nombre VARCHAR2,
                          p_correo VARCHAR2, p_f_ingreso DATE, p_puesto VARCHAR2,
                          p_sueldo NUMBER, p_depto NUMBER) IS
  BEGIN
    INSERT INTO employees(employee_id, last_name, first_name, email, hire_date, job_id, salary, department_id)
    VALUES (p_id_emp, p_apellido, p_nombre, p_correo, p_f_ingreso, p_puesto, p_sueldo, p_depto);
  END alta_empleado;

  PROCEDURE leer_empleado(p_id_emp NUMBER, p_cursor OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_cursor FOR
      SELECT *
        FROM employees
       WHERE employee_id = p_id_emp;
  END leer_empleado;

  PROCEDURE actualizar_empleado(p_id_emp NUMBER, p_apellido VARCHAR2, p_nombre VARCHAR2,
                                p_correo VARCHAR2, p_puesto VARCHAR2,
                                p_sueldo NUMBER, p_depto NUMBER) IS
  BEGIN
    UPDATE employees
       SET last_name     = COALESCE(p_apellido, last_name),
           first_name    = COALESCE(p_nombre, first_name),
           email         = COALESCE(p_correo, email),
           job_id        = COALESCE(p_puesto, job_id),
           salary        = COALESCE(p_sueldo, salary),
           department_id = COALESCE(p_depto, department_id)
     WHERE employee_id   = p_id_emp;
  END actualizar_empleado;

  PROCEDURE eliminar_empleado(p_id_emp NUMBER) IS
  BEGIN
    DELETE FROM employees WHERE employee_id = p_id_emp;
  END eliminar_empleado;

  PROCEDURE rotacion_puestos_top4(p_cursor OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_cursor FOR
      SELECT e.employee_id,
             e.last_name  AS apellido,
             e.first_name AS nombre,
             e.job_id     AS puesto_actual,
             (SELECT j.job_title FROM jobs j WHERE j.job_id = e.job_id) AS puesto_actual_desc,
             NVL((SELECT COUNT(*) FROM job_history jh WHERE jh.employee_id = e.employee_id),0) AS cambios_puesto
      FROM employees e
      ORDER BY cambios_puesto DESC, e.employee_id
      FETCH FIRST 4 ROWS ONLY;
  END rotacion_puestos_top4;

  FUNCTION promedio_contratos_mensual(p_cursor OUT SYS_REFCURSOR) RETURN NUMBER IS
    v_meses_dist INT;
  BEGIN
    OPEN p_cursor FOR
      SELECT TO_CHAR(mes_ref,'Month','NLS_DATE_LANGUAGE=English') AS mes,
             ROUND(AVG(cantidad),2) AS promedio_contrataciones
      FROM (
        SELECT TRUNC(hire_date,'MM') mes_ref, COUNT(*) cantidad
          FROM employees
         GROUP BY TRUNC(hire_date,'MM')
      )
      GROUP BY TO_CHAR(mes_ref,'Month','NLS_DATE_LANGUAGE=English'), EXTRACT(MONTH FROM mes_ref)
      ORDER BY EXTRACT(MONTH FROM mes_ref);
    SELECT COUNT(DISTINCT EXTRACT(MONTH FROM hire_date))
      INTO v_meses_dist
      FROM employees;
    RETURN v_meses_dist;
  END promedio_contratos_mensual;

  PROCEDURE reporte_regional(p_cursor OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_cursor FOR
      SELECT r.region_name AS region,
             SUM(e.salary) AS total_salarios,
             COUNT(e.employee_id) AS total_empleados,
             MIN(e.hire_date) AS primer_ingreso
        FROM regions r
        JOIN countries  c ON c.region_id   = r.region_id
        JOIN locations  l ON l.country_id  = c.country_id
        JOIN departments d ON d.location_id = l.location_id
        JOIN employees  e ON e.department_id = d.department_id
       GROUP BY r.region_name
       ORDER BY r.region_name;
  END reporte_regional;

  FUNCTION antiguedad_personal(p_cursor OUT SYS_REFCURSOR) RETURN NUMBER IS
    v_total_meses NUMBER;
  BEGIN
    OPEN p_cursor FOR
      SELECT e.employee_id,
             e.first_name,
             e.last_name,
             MONTHS_BETWEEN(TRUNC(SYSDATE), TRUNC(e.hire_date)) AS meses_servicio,
             FLOOR(MONTHS_BETWEEN(TRUNC(SYSDATE), TRUNC(e.hire_date))/12) AS anios,
             FLOOR(MONTHS_BETWEEN(TRUNC(SYSDATE), TRUNC(e.hire_date))/12) AS meses_vacaciones
        FROM employees e;

    SELECT SUM(MONTHS_BETWEEN(TRUNC(SYSDATE), TRUNC(hire_date)))
      INTO v_total_meses
      FROM employees;

    RETURN v_total_meses;
  END antiguedad_personal;

  FUNCTION dif_horas(p_inicio DATE, p_fin DATE) RETURN NUMBER IS
  BEGIN
    RETURN ROUND((p_fin - p_inicio) * 24, 2);
  END dif_horas;

  FUNCTION horas_laboradas(p_id_empleado NUMBER, p_mes NUMBER, p_anio NUMBER) RETURN NUMBER IS
    v_horas NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(dif_horas(hora_inicio_real, hora_termino_real)),0)
      INTO v_horas
      FROM asistencia_empleado a
     WHERE a.employee_id = p_id_empleado
       AND EXTRACT(MONTH FROM a.fecha_real) = p_mes
       AND EXTRACT(YEAR  FROM a.fecha_real) = p_anio
       AND a.inasistencia = 'N';
    RETURN v_horas;
  END horas_laboradas;

  FUNCTION horas_ausentes(p_id_empleado NUMBER, p_mes NUMBER, p_anio NUMBER) RETURN NUMBER IS
    v_prog NUMBER := 0;
    v_real NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(
             dif_horas(
               TO_DATE('2000-01-01','YYYY-MM-DD') + (SELECT h.hora_inicio - TRUNC(h.hora_inicio)
                                                       FROM horario h
                                                      WHERE h.dia_semana = TO_NUMBER(TO_CHAR(d,'D'))),
               TO_DATE('2000-01-01','YYYY-MM-DD') + (SELECT h.hora_termino - TRUNC(h.hora_termino)
                                                       FROM horario h
                                                      WHERE h.dia_semana = TO_NUMBER(TO_CHAR(d,'D')))
           )),0)
      INTO v_prog
      FROM (
        SELECT (TRUNC(ADD_MONTHS(DATE '2000-01-01', (p_anio-2000)*12 + (p_mes-1))) + (LEVEL-1)) d
          FROM dual
        CONNECT BY LEVEL <= EXTRACT(DAY FROM LAST_DAY(TO_DATE(p_anio||LPAD(p_mes,2,'0'),'YYYYMM')))
      ) cal
      WHERE EXISTS (
        SELECT 1
          FROM empleado_horario eh
         WHERE eh.employee_id = p_id_empleado
           AND eh.dia_semana  = TO_NUMBER(TO_CHAR(d,'D'))
      );

    v_real := horas_laboradas(p_id_empleado, p_mes, p_anio);
    RETURN GREATEST(v_prog - v_real, 0);
  END horas_ausentes;

  PROCEDURE nomina_proporcional(p_mes NUMBER, p_anio NUMBER, p_cursor OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_cursor FOR
      WITH prog AS (
        SELECT e.employee_id,
               hr_pack.horas_ausentes(e.employee_id, p_mes, p_anio)  AS hrs_falta,
               hr_pack.horas_laboradas(e.employee_id, p_mes, p_anio) AS hrs_trab
          FROM employees e
      ), base AS (
        SELECT employee_id, hrs_trab, hrs_falta, (hrs_trab + hrs_falta) AS hrs_prog
          FROM prog
      )
      SELECT e.first_name, e.last_name, e.salary,
             CASE 
               WHEN b.hrs_prog > 0 THEN ROUND(e.salary * (b.hrs_trab / b.hrs_prog), 2)
               ELSE 0
             END AS sueldo_calculado
        FROM base b
        JOIN employees e ON e.employee_id = b.employee_id
       ORDER BY sueldo_calculado DESC NULLS LAST;
  END nomina_proporcional;

  FUNCTION horas_formacion_empleado(p_id_empleado NUMBER) RETURN NUMBER IS
    v_total NUMBER;
  BEGIN
    SELECT NVL(SUM(c.horas),0)
      INTO v_total
      FROM empleado_capacitacion ec
      JOIN capacitacion c ON c.capacitacion_id = ec.capacitacion_id
     WHERE ec.employee_id = p_id_empleado;
    RETURN v_total;
  END horas_formacion_empleado;

  PROCEDURE listado_formaciones(p_cursor OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_cursor FOR
      SELECT c.capacitacion_id,
             c.nombre AS capacitacion,
             e.employee_id,
             e.first_name,
             e.last_name,
             c.horas
        FROM capacitacion c
        LEFT JOIN empleado_capacitacion ec ON ec.capacitacion_id = c.capacitacion_id
        LEFT JOIN employees e ON e.employee_id = ec.employee_id
       ORDER BY c.horas DESC, c.nombre, e.last_name, e.first_name;
  END listado_formaciones;

END hr_pack;
/

CREATE OR REPLACE TRIGGER trg_chk_asistencia
BEFORE INSERT OR UPDATE ON asistencia_empleado
FOR EACH ROW
DECLARE
  v_turno_asignado empleado_horario.turno%TYPE;
  v_plan_ini       DATE;
  v_plan_fin       DATE;
  v_dia_sem        NUMBER;
BEGIN
  v_dia_sem := TO_NUMBER(TO_CHAR(:NEW.fecha_real, 'D'));
  IF :NEW.dia_semana <> v_dia_sem THEN
    RAISE_APPLICATION_ERROR(-20001, 'Día de semana no coincide con la fecha.');
  END IF;

  SELECT eh.turno
    INTO v_turno_asignado
    FROM empleado_horario eh
   WHERE eh.employee_id = :NEW.employee_id
     AND eh.dia_semana  = :NEW.dia_semana;

  SELECT h.hora_inicio, h.hora_termino
    INTO v_plan_ini, v_plan_fin
    FROM horario h
   WHERE h.dia_semana = :NEW.dia_semana
     AND h.turno      = v_turno_asignado;

  IF :NEW.hora_inicio_real < (:NEW.fecha_real + (v_plan_ini - TRUNC(v_plan_ini)) - (30/1440))
     OR :NEW.hora_termino_real > (:NEW.fecha_real + (v_plan_fin - TRUNC(v_plan_fin)) + (30/1440)) THEN
    RAISE_APPLICATION_ERROR(-20002, 'Horas reales fuera de rango razonable respecto al plan.');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20003, 'No existe turno programado para el empleado en ese día.');
END;
/

CREATE OR REPLACE TRIGGER trg_chk_salary_range
BEFORE INSERT OR UPDATE OF salary, job_id ON employees
FOR EACH ROW
DECLARE
  v_min_aut jobs.min_salary%TYPE;
  v_max_aut jobs.max_salary%TYPE;
BEGIN
  SELECT min_salary, max_salary
    INTO v_min_aut, v_max_aut
    FROM jobs
   WHERE job_id = :NEW.job_id;

  IF :NEW.salary < v_min_aut OR :NEW.salary > v_max_aut THEN
    RAISE_APPLICATION_ERROR(-20010,
      'Salario fuera de rango para el puesto ('||:NEW.job_id||')');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_mark_inasistencia
BEFORE INSERT OR UPDATE OF hora_inicio_real, fecha_real ON asistencia_empleado
FOR EACH ROW
DECLARE
  v_turno_asignado empleado_horario.turno%TYPE;
  v_plan_ini       DATE;
  v_plan_fin       DATE;
  v_inicio_real    DATE;
  v_dia_sem        NUMBER;
BEGIN
  v_dia_sem := TO_NUMBER(TO_CHAR(:NEW.fecha_real,'D'));

  SELECT eh.turno
    INTO v_turno_asignado
    FROM empleado_horario eh
   WHERE eh.employee_id = :NEW.employee_id
     AND eh.dia_semana  = v_dia_sem;

  SELECT h.hora_inicio, h.hora_termino
    INTO v_plan_ini, v_plan_fin
    FROM horario h
   WHERE h.dia_semana = v_dia_sem
     AND h.turno      = v_turno_asignado;

  v_inicio_real := :NEW.hora_inicio_real;

  IF v_inicio_real < (:NEW.fecha_real + (v_plan_ini - TRUNC(v_plan_ini)) - (30/1440))
     OR v_inicio_real > (:NEW.fecha_real + (v_plan_ini - TRUNC(v_plan_ini)) + (30/1440)) THEN
    :NEW.inasistencia := 'S';
    :NEW.hora_termino_real := :NEW.hora_inicio_real;
  ELSE
    :NEW.inasistencia := 'N';
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    :NEW.inasistencia := 'S';
    :NEW.hora_termino_real := :NEW.hora_inicio_real;
END;
/
